---
title: "Survey Data from Individuals Teaching Abroad"
author: "Paige Harton"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: 
  html_document:
    highlights: "breezedark"
---

#input libraries
```{r, setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
library(openxlsx)
library(janitor)
library(epiDisplay)
library(ggplot2)
library(kableExtra)
library(dplyr)
library(tidyverse)
```

#read in data

```{r, read-data, echo=FALSE}
pth <- read.csv(file='data.csv, na.strings=c("", "NA"))
```

#compare confidence in host country response to COVID-19 by country
#print formatted table for comparision
#print political confidence response and display teaching countries
```{r, make-table}
tabl1 <- table(surveydata$poli_effect, surveydata$teachingcountry)

kable(tabl1, caption = "Confidence in Host Country Response to COVID-19 by Country") %>% kable_styling(bootstrap_options = c("striped", "hover"))

ggplot(surveydata, aes(poli_effect, colour = teachingcountry)) + 
  geom_histogram()
```

## End
